let
    源 = Folder.Files("D:\麻大师\日更数据\天猫旗舰店\13-ERP各渠道商品信息"),
    筛选的隐藏文件1 = Table.SelectRows(源, each [Attributes]?[Hidden]? <> true),
    调用自定义函数1 = Table.AddColumn(筛选的隐藏文件1, "转换文件 (28)", each #"转换文件 (36)"([Content])),
    重命名的列1 = Table.RenameColumns(调用自定义函数1, {"Name", "Source.Name"}),
    删除的其他列1 = Table.SelectColumns(重命名的列1, {"Source.Name", "转换文件 (28)","Date created"}),
    扩展的表格列1 = Table.ExpandTableColumn(删除的其他列1, "转换文件 (28)", Table.ColumnNames(#"转换文件 (36)"(#"示例文件 (36)"))),
    更改的类型 = Table.TransformColumnTypes(扩展的表格列1,{{"支付时间", type datetime}}),
    筛选的行 = Table.SelectRows(更改的类型, each ([商品名称] <> "补差价链接 差多少补多少 单拍不发货" and [商品名称] <> "补差链接" and [商品名称] <> "麻大师麻大师 补定制链接根据客服要求选择数量下单")),
    筛选的行4 = Table.SelectRows(筛选的行, each not Text.Contains([商品名称], "补差")),
    筛选的行1 = Table.SelectRows(筛选的行4, each ([商品编码] <> "" and [商品编码] <> "麻大师特权礼包")),
    更改的类型4 = Table.TransformColumnTypes(筛选的行1,{{"产品实付金额", type number}}),
    筛选的行3 = Table.SelectRows(更改的类型4, each ([订单状态] <> "(预售)定金罚没 交易关闭/退款成功" and [订单状态] <> "(预售)已全部支付 交易关闭/退款成功" and [订单状态] <> "(预售)已全部支付 交易成功/退款成功" and [订单状态] <> "交易关闭/退款关闭" and [订单状态] <> "交易关闭/退款成功" and [订单状态] <> "交易成功/退款成功" and [订单状态] <> "取消/京东财审通过" and [订单状态] <> "已发货/退款成功" and [订单状态] <> "已完成/退款成功" and [订单状态] <> "等待买家确认收货/退款成功" and [订单状态] <> "订单已取消/退款成功")),
    筛选的行2 = Table.SelectRows(筛选的行3, each not Text.Contains([商品名称], "小样")),
    筛选的行6 = Table.SelectRows(筛选的行2, each not Text.Contains([商品名称], "礼品袋")),
    筛选的行7 = Table.SelectRows(筛选的行6, each not Text.Contains([商品名称], "0.01元")),
    筛选的行8 = Table.SelectRows(筛选的行7, each not Text.Contains([订单状态], "退款成功")),
    筛选的行9 = Table.SelectRows(筛选的行8, each not Text.Contains([订单状态], "交易关闭")),
    更改的类型1 = Table.TransformColumnTypes(筛选的行9,{{"支付时间", type date}}),
    更改的类型2 = Table.TransformColumnTypes(更改的类型1,{{"产品实付金额", type number}, {"购买数", Int64.Type}, {"退款金额", type number}}),
    已提取分隔符之前的文本 = Table.TransformColumns(更改的类型2, {{"发货时间", each Text.BeforeDelimiter(_, " "), type text}}),
    更改的类型3 = Table.TransformColumnTypes(已提取分隔符之前的文本,{{"发货时间", type date}}),
    替换的值 = Table.ReplaceValue(更改的类型3,";"," ",Replacer.ReplaceText,{"供应商"}),
    筛选的行5 = Table.SelectRows(替换的值, each ([是否作废] <> "已作废")),
    替换的值1 = Table.ReplaceValue(筛选的行5,";","",Replacer.ReplaceText,{"平台单号"}),
    按分隔符拆分列 = Table.SplitColumn(替换的值1, "审核时间", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"审核时间.1", "审核时间.2"}),
    更改的类型5 = Table.TransformColumnTypes(按分隔符拆分列,{{"审核时间.1", type date}, {"审核时间.2", type time}, {"支付金额", type number}}),
    合并的查询 = Table.NestedJoin(更改的类型5, {"规格编码"}, #"辅10-产品编码", {"商家规编（后台）"}, "辅10-产品编码", JoinKind.LeftOuter),
    #"展开的“辅10-产品编码”" = Table.ExpandTableColumn(合并的查询, "辅10-产品编码", {"床垫类别"}, {"床垫类别"}),
    重命名的列 = Table.RenameColumns(#"展开的“辅10-产品编码”",{{"审核时间.1", "审核日期"}, {"审核时间.2", "审核时间"}}),
    删除的副本 = Table.Distinct(重命名的列, {"订单来源", "平台单号"})
in
    删除的副本