let
    源 = Folder.Files("D:\麻大师\日更数据\天猫旗舰店\02-商品明细库存表\京东pop"),
    筛选的隐藏文件1 = Table.SelectRows(源, each [Attributes]?[Hidden]? <> true),
    调用自定义函数1 = Table.AddColumn(筛选的隐藏文件1, "转换文件 (53)", each #"转换文件 (53)"([Content])),
    重命名的列1 = Table.RenameColumns(调用自定义函数1, {"Name", "Source.Name"}),
    删除的其他列1 = Table.SelectColumns(重命名的列1, {"Source.Name", "转换文件 (53)"}),
    扩展的表格列1 = Table.ExpandTableColumn(删除的其他列1, "转换文件 (53)", Table.ColumnNames(#"转换文件 (53)"(#"示例文件 (53)"))),
    更改的类型 = Table.TransformColumnTypes(扩展的表格列1,{{"Source.Name", type text}, {"订单号", type text}, {"商品ID", Int64.Type}, {"商品名称", type text}, {"订购数量", Int64.Type}, {"支付方式", type text}, {"下单时间", type datetime}, {"京东价", type number}, {"订单金额", type number}, {"结算金额", type number}, {"余额支付", Int64.Type}, {"应付金额", type number}, {"订单状态", type text}, {"订单类型", type text}, {"订单标签", type text}, {"下单帐号", type text}, {"订单备注", type text}, {"发票类型", type text}, {"发票抬头", type any}, {"发票内容", type any}, {"纳税人识别号", type any}, {"名称（个人）", type any}, {"单位地址", type any}, {"单位电话", type any}, {"开户银行", type any}, {"银行账号", type any}, {"商家备注", type text}, {"商家备注等级（等级1-5为由高到低）", Int64.Type}, {"运费金额", Int64.Type}, {"付款确认时间", type datetime}, {"货号", type text}, {"订单完成时间", type datetime}, {"订单来源", type text}, {"订单渠道", type text}, {"送装服务", type any}, {"服务费", type any}, {"仓库id", Int64.Type}, {"仓库名称", type text}, {"商家SKUID", type text}, {"邮箱地址", type text}, {"邮政编码", type any}, {"是否为品牌商订单", type any}, {"是否为toplife订单", type any}, {"业务类型", type any}, {"履约门店ID", type any}, {"下单门店Id", type any}, {"门店名称", type any}, {"门店联系人", type any}, {"门店联系电话", type any}, {"门店地址", type any}, {"导购员账号", type any}, {"延迟报备类型", type text}, {"订单出库时间", type datetime}, {"客户类型", type text}, {"KA订单发货需提供单据", type any}, {"KA订单客户收货要求", type any}, {"正品鉴定校验结果", type any}, {"正品鉴定补充说明", type any}, {"正品鉴定不合格原因", type any}, {"正品鉴定图片链接", type any}, {"企配订单", type text}, {"需上传SN码", type text}, {"SN码", type any}, {"SN码有效状态", type any}, {"SN码激活状态", type any}, {"SN码补贴状态", type any}, {"百补满赠", type any}, {"买一试三", type text}, {"承诺发货时间", type text}, {"款项名称", type any}, {"项目ID", type any}, {"指数订单编号", type any}, {"是否为以旧换新订单", type text}, {"主体ID", type any}, {"主体名称", type any}, {"采购价", type any}, {"采购订单号", type any}}),
    重命名的列 = Table.RenameColumns(更改的类型,{{"商品名称", "商品标题"}, {"订购数量", "购买数量"}, {"商家SKUID", "商家编码"}, {"应付金额", "买家应付货款"}, {"下单时间", "订单付款时间"}, {"承诺发货时间", "应发货时间"}, {"订单号", "主订单编号"}})
in
    重命名的列