let
    源 = Folder.Files("D:\麻大师\日更数据\天猫旗舰店\04-旗舰店基础数据"),
    筛选的隐藏文件1 = Table.SelectRows(源, each [Attributes]?[Hidden]? <> true),
    调用自定义函数1 = Table.AddColumn(筛选的隐藏文件1, "转换文件 (15)", each #"转换文件 (15)"([Content])),
    重命名的列1 = Table.RenameColumns(调用自定义函数1, {"Name", "Source.Name"}),
    删除的其他列1 = Table.SelectColumns(重命名的列1, {"Source.Name", "转换文件 (15)"}),
    扩展的表格列1 = Table.ExpandTableColumn(删除的其他列1, "转换文件 (15)", Table.ColumnNames(#"转换文件 (15)"(#"示例文件 (15)"))),
    更改的类型 = Table.TransformColumnTypes(扩展的表格列1,{{"Source.Name", type text}, {"统计日期", type date}, {"店铺名称", type text}, {"访客数", Int64.Type}, {"直播间访客数", Int64.Type}, {"短视频访客数", Int64.Type}, {"图文访客数", Int64.Type}, {"店铺页访客数", Int64.Type}, {"3D应用访客数", Int64.Type}, {"无线端访客数", Int64.Type}, {"PC端访客数", Int64.Type}, {"浏览量", Int64.Type}, {"无线端浏览量", Int64.Type}, {"PC端浏览量", Int64.Type}, {"商品访客数", Int64.Type}, {"无线端商品访客数", Int64.Type}, {"PC端商品访客数", Int64.Type}, {"商品浏览量", Int64.Type}, {"无线端商品浏览量", Int64.Type}, {"PC端商品浏览量", Int64.Type}, {"平均停留时长", type number}, {"无线端平均停留时长", type number}, {"PC端平均停留时长", type number}, {"跳失率", type number}, {"无线端跳失率", type number}, {"PC端跳失率", type number}, {"商品收藏买家数", Int64.Type}, {"无线端商品收藏买家数", Int64.Type}, {"PC端商品收藏买家数", Int64.Type}, {"商品收藏次数", Int64.Type}, {"无线端商品收藏次数", Int64.Type}, {"PC端商品收藏次数", Int64.Type}, {"加购人数", Int64.Type}, {"无线端加购人数", Int64.Type}, {"PC端加购人数", Int64.Type}, {"支付金额", type number}, {"无线端支付金额", type number}, {"PC端支付金额", type number}, {"支付买家数", Int64.Type}, {"无线端支付买家数", Int64.Type}, {"PC端支付买家数", Int64.Type}, {"支付子订单数", Int64.Type}, {"无线端支付子订单数", Int64.Type}, {"PC端支付子订单数", Int64.Type}, {"支付件数", Int64.Type}, {"无线端支付件数", Int64.Type}, {"PC端支付件数", Int64.Type}, {"下单金额", type number}, {"无线端下单金额", type number}, {"PC端下单金额", type number}, {"下单买家数", Int64.Type}, {"无线端下单买家数", Int64.Type}, {"PC端下单买家数", Int64.Type}, {"下单件数", Int64.Type}, {"无线端下单件数", Int64.Type}, {"PC端下单件数", Int64.Type}, {"人均浏览量", type number}, {"无线端人均浏览量", type number}, {"PC端人均浏览量", type number}, {"下单转化率", type number}, {"无线端下单转化率", type number}, {"PC端下单转化率", type number}, {"支付转化率", type number}, {"无线端支付转化率", type number}, {"PC端支付转化率", type number}, {"客单价", type number}, {"无线端客单价", type number}, {"PC端客单价", type number}, {"UV价值", type number}, {"无线端UV价值", type number}, {"PC端UV价值", type any}, {"老访客数", Int64.Type}, {"无线端老访客数", Int64.Type}, {"PC端老访客数", Int64.Type}, {"新访客数", Int64.Type}, {"无线端新访客数", Int64.Type}, {"PC端新访客数", Int64.Type}, {"加购件数", Int64.Type}, {"无线端加购件数", Int64.Type}, {"PC端加购件数", Int64.Type}, {"支付新买家数", Int64.Type}, {"支付老买家数", Int64.Type}, {"无线端支付老买家数", Int64.Type}, {"PC端支付老买家数", Int64.Type}, {"老买家支付金额", type number}, {"全站推广花费", type number}, {"关键词推广花费", type number}, {"精准人群推广花费", type number}, {"智能场景花费", type number}, {"淘宝客佣金", type number}, {"成功退款金额", type number}, {"评价数", Int64.Type}, {"有图评价数", Int64.Type}, {"正面评价数", Int64.Type}, {"负面评价数", Int64.Type}, {"老买家正面评价数", Int64.Type}, {"老买家负面评价数", Int64.Type}, {"支付父订单数", Int64.Type}, {"揽收包裹数", Int64.Type}, {"发货包裹数", Int64.Type}, {"派送包裹数", Int64.Type}, {"签收成功包裹数", Int64.Type}, {"平均支付_签收时长(秒)", type number}, {"描述相符评分", type number}, {"物流服务评分", type number}, {"服务态度评分", type number}, {"下单-支付转化率", type number}, {"无线端下单-支付转化率", type number}, {"PC端下单-支付转化率", type number}, {"支付商品数", Int64.Type}, {"无线端支付商品数", Int64.Type}, {"PC端支付商品数", Int64.Type}, {"关注店铺人数", Int64.Type}, {"无线端关注店铺人数", Int64.Type}, {"PC端关注店铺人数", Int64.Type}, {"会员总数", Int64.Type}, {"新增会员数", Int64.Type}, {"活跃会员数", Int64.Type}, {"会员成交金额", type number}, {"会员成交人数", Int64.Type}}),
    删除的副本 = Table.Distinct(更改的类型, {"统计日期", "店铺名称", "访客数", "直播间访客数", "短视频访客数"}),
    重命名的列 = Table.RenameColumns(删除的副本,{{"客单价", "客单价（固数））"}, {"UV价值", "UV价值（固数）"}, {"支付转化率", "支付转化率（固数）"}})
in
    重命名的列
