table 03-1-各渠道目标金额
	excludeFromModelRefresh
	lineageTag: 2ffdb45e-42fa-4dd4-bb90-5936ff1fcd61

	measure MTD目标 =
			
			divide(CALCULATE (
			    sum('03-1-各渠道目标金额'[值]), // 替换为你的实际度量值，如[商品花费占比]
			    DATESMTD ( '01-店铺数据辅助表'[日期] ) // 计算月初到筛选日期的累计
			),10000)
		lineageTag: 38348b82-daf5-4697-a533-0ae48a33d3e1

		formatStringDefinition = "0.00万"

	measure 月度任务完成率 = divide([回款金额（万）MTD],[MTD目标])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d8b70b2a-d6d6-4265-bf71-a979593c8563

	column 渠道
		dataType: string
		lineageTag: ce16b39f-78a4-4164-b902-b06205003065
		summarizeBy: none
		sourceColumn: 渠道

		annotation SummarizationSetBy = Automatic

	column 店铺
		dataType: string
		lineageTag: a16b8f5f-ed75-4a0a-a615-1dc8f468ef06
		summarizeBy: none
		sourceColumn: 店铺

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: be6bf273-7f40-49c9-9dae-36bbab99a9e6
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 值
		dataType: int64
		formatString: 0
		lineageTag: 1d5af6ac-b41c-4096-9287-5fee14536409
		summarizeBy: sum
		sourceColumn: 值

		annotation SummarizationSetBy = Automatic

	partition 03-1-各渠道目标金额 = m
		mode: import
		source =
				let
				    源 = Excel.Workbook(File.Contents("D:\麻大师\日更数据\天猫旗舰店\00-各渠道销售数据\25年各渠道目标.xlsx"), null, false),
				    Sheet1_sheet = 源{[Item="Sheet1",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    删除的底部行 = Table.RemoveLastN(Sheet1_sheet, each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    更改的类型 = Table.TransformColumnTypes(删除的底部行,{{"Column1", type text}, {"Column2", type text}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}}),
				    提升的标题 = Table.PromoteHeaders(更改的类型, [PromoteAllScalars=true]),
				    更改的类型1 = Table.TransformColumnTypes(提升的标题,{{"渠道", type text}, {"店铺", type text}, {"1月", Int64.Type}, {"2月", Int64.Type}, {"3月", Int64.Type}, {"4月", Int64.Type}, {"5月", Int64.Type}, {"6月", Int64.Type}, {"7月", Int64.Type}, {"8月", Int64.Type}, {"9月", Int64.Type}, {"10月", Int64.Type}, {"11月", Int64.Type}, {"12月", Int64.Type}}),
				    逆透视的列 = Table.UnpivotOtherColumns(更改的类型1, {"渠道", "店铺"}, "属性", "值"),
				    更改的类型2 = Table.TransformColumnTypes(逆透视的列,{{"属性", type date}}),
				    重命名的列 = Table.RenameColumns(更改的类型2,{{"属性", "日期"}})
				in
				    重命名的列

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

