table 03-2店铺每天销售目标
	excludeFromModelRefresh
	lineageTag: 0598383b-ce7e-4c73-9b35-eb994eba97bc

	measure 销售目标（万） = DIVIDE(SUM('03-2店铺每天销售目标'[销售目标]), 10000)
		lineageTag: 496cff1e-ce4e-4c4a-97fa-219583e43bd3

		formatStringDefinition = "0.00万"

	column 'Source.Name'
		dataType: string
		lineageTag: a5a42a96-8485-46e2-a500-2ad04bcb5fc1
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: d5e242cc-97ee-4799-a43c-2d8d4d523b60
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 销售目标
		dataType: int64
		formatString: "¥"#,0;"¥"-#,0;"¥"#,0
		lineageTag: e35e96fe-dc5a-4e74-b468-04483a5f4be2
		summarizeBy: sum
		sourceColumn: 销售目标

		annotation SummarizationSetBy = Automatic

	column 旗舰店毛利
		dataType: int64
		formatString: 0
		lineageTag: 06be00a6-a6c3-4bb7-bd91-30150f4b762c
		summarizeBy: sum
		sourceColumn: 旗舰店毛利

		annotation SummarizationSetBy = Automatic

	partition 03-2店铺每天销售目标 = m
		mode: import
		source =
				let
				    源 = Folder.Files("D:\麻大师\日更数据\天猫旗舰店\03-各店铺销售目标"),
				    筛选的隐藏文件1 = Table.SelectRows(源, each [Attributes]?[Hidden]? <> true),
				    调用自定义函数1 = Table.AddColumn(筛选的隐藏文件1, "转换文件 (16)", each #"转换文件 (16)"([Content])),
				    重命名的列1 = Table.RenameColumns(调用自定义函数1, {"Name", "Source.Name"}),
				    删除的其他列1 = Table.SelectColumns(重命名的列1, {"Source.Name", "转换文件 (16)"}),
				    扩展的表格列1 = Table.ExpandTableColumn(删除的其他列1, "转换文件 (16)", Table.ColumnNames(#"转换文件 (16)"(#"示例文件 (16)"))),
				    更改的类型 = Table.TransformColumnTypes(扩展的表格列1,{{"Source.Name", type text}, {"日期", type date}, {"销售目标", Int64.Type}, {"旗舰店毛利", Int64.Type}, {"Column4", type any}}),
				    删除的列 = Table.RemoveColumns(更改的类型,{"Column4"})
				in
				    删除的列

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

