table 10-4客服员工日报统计
	lineageTag: 21186dc4-d41d-40dc-b111-33f980d519e7

	measure 京东答问比 = DIVIDE(sum('10-4客服员工日报统计'[客服总消息数]),sum('10-4客服员工日报统计'[客户总消息数]))
		lineageTag: 7aff1359-d812-4275-ab88-595b0f0664a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 京东答问比环比 =
			
			VAR CurrentValue = [京东答问比]
			VAR PreviousValue = CALCULATE( [京东答问比], DATEADD('01-店铺数据辅助表'[日期].[Date], -1 , DAY ))
			RETURN
			DIVIDE(CurrentValue - PreviousValue, PreviousValue, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8bf1fb05-ba2b-4911-8de2-0719829ea29c

	measure 好评环比 =
			
			VAR CurrentValue =SUM('10-4客服员工日报统计'[好评量])
			VAR PreviousValue = CALCULATE(SUM('10-4客服员工日报统计'[好评量]), DATEADD('01-店铺数据辅助表'[日期].[Date], -1 , DAY ))
			RETURN
			DIVIDE(CurrentValue - PreviousValue, PreviousValue, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0ccbb5ce-06db-45de-b694-5ddc1ef04d32

	measure 差评环比 =
			
			VAR CurrentValue = SUM('10-4客服员工日报统计'[差评量])
			VAR PreviousValue = CALCULATE(SUM('10-4客服员工日报统计'[差评量]), DATEADD('01-店铺数据辅助表'[日期].[Date], -1 , DAY ))
			RETURN
			DIVIDE(CurrentValue - PreviousValue, PreviousValue, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2fba9b19-f121-485b-ba41-128a0597c112

	column 'Source.Name'
		dataType: string
		lineageTag: edb0ebb8-0253-4fdb-9c88-0707978828ff
		summarizeBy: none
		sourceColumn: Source.Name

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2eb1dfd3-3a77-43dc-a237-400e9b3f848c
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UID
		dataType: string
		lineageTag: 0c366031-a504-49d3-b773-872c6c28b20a
		summarizeBy: none
		sourceColumn: UID

		annotation SummarizationSetBy = Automatic

	column 技能组
		dataType: string
		lineageTag: 50930dc6-ac66-4f10-9607-10249b8ff07c
		summarizeBy: none
		sourceColumn: 技能组

		annotation SummarizationSetBy = Automatic

	column 服务商
		dataType: string
		lineageTag: d36687f7-1127-43ab-9947-849d61718eb6
		summarizeBy: none
		sourceColumn: 服务商

		annotation SummarizationSetBy = Automatic

	column ERP
		dataType: string
		lineageTag: 321f42b7-328b-4808-a3c6-54a408f10893
		summarizeBy: none
		sourceColumn: ERP

		annotation SummarizationSetBy = Automatic

	column 咨询量
		dataType: int64
		formatString: 0
		lineageTag: 377e6ede-4964-4204-9dca-a4f4d1c38c0c
		summarizeBy: sum
		sourceColumn: 咨询量

		annotation SummarizationSetBy = Automatic

	column 接待量
		dataType: int64
		formatString: 0
		lineageTag: ba0106b0-1feb-45a8-bf6f-fcd206363f2c
		summarizeBy: sum
		sourceColumn: 接待量

		annotation SummarizationSetBy = Automatic

	column 转出量
		dataType: int64
		formatString: 0
		lineageTag: d5d7f7fe-f226-4f54-ad07-b68b102c89d9
		summarizeBy: sum
		sourceColumn: 转出量

		annotation SummarizationSetBy = Automatic

	column 转入量
		dataType: int64
		formatString: 0
		lineageTag: d1590fcd-de90-4595-aa7d-bd74e5a31e2a
		summarizeBy: sum
		sourceColumn: 转入量

		annotation SummarizationSetBy = Automatic

	column 评价总数
		dataType: int64
		formatString: 0
		lineageTag: 28f61096-0c28-4bc3-af78-1e06daa4c404
		summarizeBy: sum
		sourceColumn: 评价总数

		annotation SummarizationSetBy = Automatic

	column 勋章评价
		dataType: int64
		formatString: 0
		lineageTag: d1e116da-db5e-4d27-82a5-8a4eba8acd0a
		summarizeBy: sum
		sourceColumn: 勋章评价

		annotation SummarizationSetBy = Automatic

	column 非常满意
		dataType: int64
		formatString: 0
		lineageTag: 765dd8bc-1e7e-4fb7-a9bc-2ee0516d6550
		summarizeBy: sum
		sourceColumn: 非常满意

		annotation SummarizationSetBy = Automatic

	column 满意
		dataType: int64
		formatString: 0
		lineageTag: a3ce4f2b-bb33-433b-8b95-ad7fae73ce95
		summarizeBy: sum
		sourceColumn: 满意

		annotation SummarizationSetBy = Automatic

	column 一般
		dataType: int64
		formatString: 0
		lineageTag: a01ceab1-2842-4cf6-8ffd-19e6f4db44c0
		summarizeBy: sum
		sourceColumn: 一般

		annotation SummarizationSetBy = Automatic

	column 不满意
		dataType: int64
		formatString: 0
		lineageTag: 825e93bd-d036-4d9f-bfd7-8083f03fc71c
		summarizeBy: sum
		sourceColumn: 不满意

		annotation SummarizationSetBy = Automatic

	column 非常不满意
		dataType: int64
		formatString: 0
		lineageTag: 070b253e-b111-4736-ba1f-641ea92e0592
		summarizeBy: sum
		sourceColumn: 非常不满意

		annotation SummarizationSetBy = Automatic

	column 评价率
		dataType: string
		lineageTag: 81bd45ab-8f3e-4035-8787-304206bc08b0
		summarizeBy: none
		sourceColumn: 评价率

		annotation SummarizationSetBy = Automatic

	column 满意率
		dataType: string
		lineageTag: 55b13642-427b-4990-a502-49ff75c4f817
		summarizeBy: none
		sourceColumn: 满意率

		annotation SummarizationSetBy = Automatic

	column 不满意率
		dataType: string
		lineageTag: 73e7470a-c740-447b-822c-e1554749b46e
		summarizeBy: none
		sourceColumn: 不满意率

		annotation SummarizationSetBy = Automatic

	column 一次性解决量
		dataType: string
		lineageTag: a334518c-811a-4312-b7f2-35b1dcb0838b
		summarizeBy: none
		sourceColumn: 一次性解决量

		annotation SummarizationSetBy = Automatic

	column 一次性解决率
		dataType: string
		lineageTag: e83ae990-c472-4200-92a2-d83815a686a2
		summarizeBy: none
		sourceColumn: 一次性解决率

		annotation SummarizationSetBy = Automatic

	column 4次以下会话数
		dataType: int64
		formatString: 0
		lineageTag: 7076a895-9b52-4e3b-87fe-690198dfb3f2
		summarizeBy: sum
		sourceColumn: 4次以下会话数

		annotation SummarizationSetBy = Automatic

	column '4- 10 次会话数'
		dataType: int64
		formatString: 0
		lineageTag: 4dec8c4f-a9bd-4cb9-be8b-66da09dd385d
		summarizeBy: sum
		sourceColumn: 4- 10 次会话数

		annotation SummarizationSetBy = Automatic

	column 10次以上会话数
		dataType: int64
		formatString: 0
		lineageTag: 1679fd8a-96fa-44cc-b719-42245f018ad7
		summarizeBy: sum
		sourceColumn: 10次以上会话数

		annotation SummarizationSetBy = Automatic

	column 客户总消息数
		dataType: int64
		formatString: 0
		lineageTag: b0b0fabf-ddc4-44d0-8e85-a672051fe0c3
		summarizeBy: sum
		sourceColumn: 客户总消息数

		annotation SummarizationSetBy = Automatic

	column 客服总消息数
		dataType: int64
		formatString: 0
		lineageTag: 8bd6cedf-c1b5-4f82-b02d-b0d6c4386587
		summarizeBy: sum
		sourceColumn: 客服总消息数

		annotation SummarizationSetBy = Automatic

	column 邀评数
		dataType: int64
		formatString: 0
		lineageTag: e4b963f0-a3e3-4ca8-bee6-c5f70138ce98
		summarizeBy: sum
		sourceColumn: 邀评数

		annotation SummarizationSetBy = Automatic

	column 邀评率
		dataType: string
		lineageTag: 4d9edf02-8836-4c61-ae0e-72937de37d3f
		summarizeBy: none
		sourceColumn: 邀评率

		annotation SummarizationSetBy = Automatic

	column CPH时长
		dataType: int64
		formatString: 0
		lineageTag: 9e571702-47ed-4d96-9294-1f8729b33028
		summarizeBy: sum
		sourceColumn: CPH时长

		annotation SummarizationSetBy = Automatic

	column 会话时长
		dataType: double
		lineageTag: 757d2aca-3bb8-474b-be41-61f811200776
		summarizeBy: sum
		sourceColumn: 会话时长

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 首次应答时长
		dataType: double
		lineageTag: 7392522d-28ae-4e41-a3e3-aed768096ff7
		summarizeBy: sum
		sourceColumn: 首次应答时长

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 留言分配量
		dataType: int64
		formatString: 0
		lineageTag: 619bfb35-47f3-42ab-b031-8984e1a55831
		summarizeBy: sum
		sourceColumn: 留言分配量

		annotation SummarizationSetBy = Automatic

	column 留言接待量
		dataType: int64
		formatString: 0
		lineageTag: f4ca3c54-f552-4cbf-a887-42c9d39ffce1
		summarizeBy: sum
		sourceColumn: 留言接待量

		annotation SummarizationSetBy = Automatic

	column 留言响应率
		dataType: string
		lineageTag: f23111b2-50ee-4dd9-839f-a8711995c6fc
		summarizeBy: none
		sourceColumn: 留言响应率

		annotation SummarizationSetBy = Automatic

	column 平均响应时间
		dataType: double
		lineageTag: ed410123-173f-4b1b-b805-5b80563980c9
		summarizeBy: sum
		sourceColumn: 平均响应时间

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 30s应答率
		dataType: double
		lineageTag: 8b55d150-bae2-4d42-9b9a-866ea7900abb
		summarizeBy: sum
		sourceColumn: 30s应答率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 好评量
		dataType: double
		lineageTag: a493c633-6ede-4ab1-b8d6-36ac2accbce4
		summarizeBy: sum
		sourceColumn: 好评量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 差评量
		dataType: double
		lineageTag: 5094c827-87d8-4aa5-817e-c1a64da56212
		summarizeBy: sum
		sourceColumn: 差评量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工作时间段咨询量
		dataType: double
		lineageTag: 6152bfb0-0eca-4521-81d9-7a6622baa044
		summarizeBy: sum
		sourceColumn: 工作时间段咨询量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 全天咨询量
		dataType: double
		lineageTag: b64c14fa-2d40-4105-9579-16598390c096
		summarizeBy: sum
		sourceColumn: 全天咨询量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 首次30s接待量
		dataType: double
		lineageTag: 949060cb-4351-4049-874d-da2717772131
		summarizeBy: sum
		sourceColumn: 首次30s接待量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 首次30s应答率
		dataType: double
		lineageTag: 111c7b98-2700-459b-9961-0c604cd83f4d
		summarizeBy: sum
		sourceColumn: 首次30s应答率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工作时间段无响应量
		dataType: double
		formatString: 0
		lineageTag: 4d8f7653-3adc-49c2-9e62-cb343da65f99
		summarizeBy: sum
		sourceColumn: 工作时间段无响应量

		annotation SummarizationSetBy = Automatic

	column 新平均响应时间
		dataType: double
		lineageTag: 1e98be96-cfa9-4234-be93-b223f3e0f07e
		summarizeBy: sum
		sourceColumn: 新平均响应时间

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 咨询差评率
		dataType: double
		lineageTag: f39eab57-d421-4c07-a144-0d9dfd3b937b
		summarizeBy: sum
		sourceColumn: 咨询差评率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 3分钟人工回复量
		dataType: double
		formatString: 0
		lineageTag: 24ae84da-7d8f-4e09-8332-352c07f0b658
		summarizeBy: sum
		sourceColumn: 3分钟人工回复量

		annotation SummarizationSetBy = Automatic

	column 3分钟回复率（客服维度-不含留言）
		dataType: string
		lineageTag: 28e66412-6ec5-461e-a3f5-7d3ebb3f89b8
		summarizeBy: none
		sourceColumn: 3分钟回复率（客服维度-不含留言）

		annotation SummarizationSetBy = Automatic

	partition 10-4客服员工日报统计 = m
		mode: import
		source =
				let
				    源 = Folder.Files("D:\麻大师\日更数据\天猫旗舰店\10-2京东客服绩效明细\客服员工日报统计"),
				    筛选的隐藏文件1 = Table.SelectRows(源, each [Attributes]?[Hidden]? <> true),
				    调用自定义函数1 = Table.AddColumn(筛选的隐藏文件1, "转换文件 (40)", each #"转换文件 (40)"([Content])),
				    重命名的列1 = Table.RenameColumns(调用自定义函数1, {"Name", "Source.Name"}),
				    删除的其他列1 = Table.SelectColumns(重命名的列1, {"Source.Name", "转换文件 (40)"}),
				    扩展的表格列1 = Table.ExpandTableColumn(删除的其他列1, "转换文件 (40)", Table.ColumnNames(#"转换文件 (40)"(#"示例文件 (40)"))),
				    更改的类型2 = Table.TransformColumnTypes(扩展的表格列1,{{"非常满意", type number}, {"满意", type number}, {"不满意", type number}, {"非常不满意", type number}}),
				    已添加自定义 = Table.AddColumn(更改的类型2, "好评量", each [非常满意]+[满意]),
				    已添加自定义1 = Table.AddColumn(已添加自定义, "差评量", each [不满意]+[非常不满意]),
				    追加的查询 = Table.Combine({已添加自定义1, 考勤数据}),
				    更改的类型1 = Table.TransformColumnTypes(追加的查询,{{"好评量", type number}, {"差评量", type number}}),
				    替换的值 = Table.ReplaceValue(更改的类型1,null,0,Replacer.ReplaceValue,{"Source.Name", "日期", "UID", "技能组", "服务商", "ERP", "咨询量", "接待量", "转出量", "转入量", "评价总数", "勋章评价", "非常满意", "满意", "一般", "不满意", "非常不满意", "评价率", "满意率", "不满意率", "一次性解决量", "一次性解决率", "4次以下会话数", "4- 10 次会话数", "10次以上会话数", "客户总消息数", "客服总消息数", "邀评数", "邀评率", "CPH时长", "会话时长", "首次应答时长", "留言分配量", "留言接待量", "留言响应率", "平均响应时间", "30s应答率", "好评量", "差评量", "工作时间段咨询量", "全天咨询量", "首次30s接待量", "首次30s应答率", "工作时间段无响应量", "新平均响应时间", "咨询差评率", "3分钟人工回复量", "3分钟回复率（客服维度-不含留言）"}),
				    更改的类型 = Table.TransformColumnTypes(替换的值,{{"Source.Name", type text}, {"日期", type date}, {"UID", type text}, {"技能组", type text}, {"服务商", type text}, {"ERP", type any}, {"咨询量", Int64.Type}, {"接待量", Int64.Type}, {"转出量", Int64.Type}, {"转入量", Int64.Type}, {"评价总数", Int64.Type}, {"勋章评价", Int64.Type}, {"非常满意", Int64.Type}, {"满意", Int64.Type}, {"一般", Int64.Type}, {"不满意", Int64.Type}, {"非常不满意", Int64.Type}, {"评价率", type text}, {"满意率", type text}, {"不满意率", type text}, {"一次性解决量", type any}, {"一次性解决率", type any}, {"4次以下会话数", Int64.Type}, {"4- 10 次会话数", Int64.Type}, {"10次以上会话数", Int64.Type}, {"客户总消息数", Int64.Type}, {"客服总消息数", Int64.Type}, {"邀评数", Int64.Type}, {"邀评率", type text}, {"CPH时长", Int64.Type}, {"会话时长", type number}, {"首次应答时长", type number}, {"留言分配量", Int64.Type}, {"留言接待量", Int64.Type}, {"留言响应率", type text}, {"平均响应时间", type number}, {"30s应答率", Percentage.Type}}),
				    删除的副本 = Table.Distinct(更改的类型, {"日期", "UID", "技能组", "服务商"})
				in
				    删除的副本

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

