table 淘宝客服排班表
	excludeFromModelRefresh
	lineageTag: 33d10dca-9feb-4584-86ab-66db5bdccda8

	column '客服排班表.xlsx'
		dataType: string
		lineageTag: 0607b00e-96fb-4cf6-b64b-2aaf03f920fd
		summarizeBy: none
		sourceColumn: 客服排班表.xlsx

		annotation SummarizationSetBy = Automatic

	column 旺旺昵称
		dataType: string
		lineageTag: 89b15cde-453a-4032-9032-7feb2b08175d
		summarizeBy: none
		sourceColumn: 旺旺昵称

		annotation SummarizationSetBy = Automatic

	column 班次
		dataType: string
		lineageTag: 635ca1e9-9588-4670-ba01-0eb687790230
		summarizeBy: none
		sourceColumn: 班次

		annotation SummarizationSetBy = Automatic

	column 昵称
		dataType: string
		lineageTag: 63eb8f5b-9acd-4cd3-8af8-4a67f39b017e
		summarizeBy: none
		sourceColumn: 昵称

		annotation SummarizationSetBy = Automatic

	column 分组
		dataType: string
		lineageTag: 94231cb0-d0e5-497f-933d-826aeea55cdd
		summarizeBy: none
		sourceColumn: 分组

		annotation SummarizationSetBy = Automatic

	column 开始时间
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2da243c0-cff0-4135-8eb1-8b1072b0b904
		summarizeBy: none
		sourceColumn: 开始时间

		variation 变体
			isDefault
			relationship: 79ebe40a-f653-4ad0-994f-d0696b007673
			defaultHierarchy: LocalDateTable_a14edd28-e245-4816-92b5-f75d0784466b.日期层次结构

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 结束时间
		dataType: dateTime
		formatString: Long Date
		lineageTag: bba3229a-127d-496f-a1fd-34abd0031690
		summarizeBy: none
		sourceColumn: 结束时间

		variation 变体
			isDefault
			relationship: d0c3aa08-9342-472c-af93-ad2eab4fcac8
			defaultHierarchy: LocalDateTable_ee832b9e-1a6c-43a9-97b5-c11eb130180a.日期层次结构

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Column8
		dataType: string
		lineageTag: 0d7c6a52-37fa-44e7-9edc-608a391f8493
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: 056228cf-a390-40bc-873a-a2dcd5690dc4
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: b9137d63-6603-4985-8e80-7bfc9de3b54d
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	partition 淘宝客服排班表 = m
		mode: import
		source =
				let
				    源 = Folder.Files("D:\麻大师\日更数据\天猫旗舰店\淘宝客服排班表"),
				    筛选的隐藏文件1 = Table.SelectRows(源, each [Attributes]?[Hidden]? <> true),
				    调用自定义函数1 = Table.AddColumn(筛选的隐藏文件1, "转换文件 (31)", each #"转换文件 (31)"([Content])),
				    重命名的列1 = Table.RenameColumns(调用自定义函数1, {"Name", "Source.Name"}),
				    删除的其他列1 = Table.SelectColumns(重命名的列1, {"Source.Name", "转换文件 (31)"}),
				    扩展的表格列1 = Table.ExpandTableColumn(删除的其他列1, "转换文件 (31)", Table.ColumnNames(#"转换文件 (31)"(#"示例文件 (31)"))),
				    更改的类型 = Table.TransformColumnTypes(扩展的表格列1,{{"Source.Name", type text}, {"Column1", type text}, {"Column2", type text}}),
				    提升的标题 = Table.PromoteHeaders(更改的类型, [PromoteAllScalars=true]),
				    更改的类型1 = Table.TransformColumnTypes(提升的标题,{{"客服排班表.xlsx", type text}, {"旺旺昵称", type text}, {"班次", type text}, {"昵称", type text}, {"开始时间", type date}, {"结束时间", type date}})
				in
				    更改的类型1

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Exception

