table 考勤数据
	isHidden
	lineageTag: 13bae4b1-a988-4e82-aa40-e9d6ce59246d

	column 'Source.Name'
		dataType: string
		isHidden
		lineageTag: 2ff7d86f-540e-4088-a15b-409b60b122db
		summarizeBy: none
		sourceColumn: Source.Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 工作时间段咨询量
		dataType: double
		isHidden
		lineageTag: 5a4e964a-793a-4e74-afdb-11126ac817b4
		summarizeBy: sum
		sourceColumn: 工作时间段咨询量

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 全天咨询量
		dataType: double
		isHidden
		lineageTag: be270626-192e-4946-ac94-861b67b38bb5
		summarizeBy: sum
		sourceColumn: 全天咨询量

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 接待量
		dataType: double
		isHidden
		lineageTag: b1448513-6aba-4f78-b070-0a265805f919
		summarizeBy: sum
		sourceColumn: 接待量

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 首次30s接待量
		dataType: double
		isHidden
		lineageTag: e363dc7c-e274-45ee-8507-6a6dc92fc4e5
		summarizeBy: sum
		sourceColumn: 首次30s接待量

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 首次30s应答率
		dataType: double
		isHidden
		lineageTag: 279b4e2e-dfc5-4fad-9af3-71a6ee2bcb0e
		summarizeBy: sum
		sourceColumn: 首次30s应答率

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工作时间段无响应量
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 03e077b9-b92d-47ed-8f87-08ef29a80bf5
		summarizeBy: sum
		sourceColumn: 工作时间段无响应量

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 满意率
		dataType: string
		isHidden
		lineageTag: 35e38eb7-a51e-4abc-a23c-ae705c96da2f
		summarizeBy: none
		sourceColumn: 满意率

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 好评量
		dataType: double
		isHidden
		lineageTag: 9e43ec15-0fab-4fe7-8f6d-ba2786358098
		summarizeBy: sum
		sourceColumn: 好评量

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 差评量
		dataType: double
		isHidden
		lineageTag: c2a65d56-a02b-4951-a5ad-46f8560b57e8
		summarizeBy: sum
		sourceColumn: 差评量

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 平均响应时间
		dataType: double
		isHidden
		lineageTag: dcde029e-3a90-44f2-b709-fbf5ff779ecc
		summarizeBy: sum
		sourceColumn: 平均响应时间

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 新平均响应时间
		dataType: double
		isHidden
		lineageTag: 8d54f6eb-c7d5-418e-9adf-c715e5ce7c05
		summarizeBy: sum
		sourceColumn: 新平均响应时间

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 咨询差评率
		dataType: double
		isHidden
		lineageTag: 26e2be3c-bacc-4afd-82d7-faa793678a2e
		summarizeBy: sum
		sourceColumn: 咨询差评率

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 3分钟人工回复量
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5c274b12-5359-4deb-b883-a0b584d0f035
		summarizeBy: sum
		sourceColumn: 3分钟人工回复量

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 3分钟回复率（客服维度-不含留言）
		dataType: string
		isHidden
		lineageTag: 31641a09-cb5a-439f-b548-4ff9ce3eb4e6
		summarizeBy: none
		sourceColumn: 3分钟回复率（客服维度-不含留言）

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: string
		isHidden
		lineageTag: 74a59ac6-2f7b-4eff-961f-256177c70f1b
		summarizeBy: none
		sourceColumn: 日期

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UID
		dataType: string
		isHidden
		lineageTag: 8c6e287f-93db-413f-aa2a-c717d77e515b
		summarizeBy: none
		sourceColumn: UID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 考勤数据 = m
		mode: import
		source = ```
				let
				    源 = Folder.Files("D:\麻大师\日更数据\天猫旗舰店\10-2京东客服绩效明细\考勤数据"),
				    筛选的隐藏文件1 = Table.SelectRows(源, each [Attributes]?[Hidden]? <> true),
				    调用自定义函数1 = Table.AddColumn(筛选的隐藏文件1, "转换文件 (47)", each #"转换文件 (47)"([Content])),
				    重命名的列1 = Table.RenameColumns(调用自定义函数1, {"Name", "Source.Name"}),
				    删除的其他列1 = Table.SelectColumns(重命名的列1, {"Source.Name", "转换文件 (47)"}),
				    扩展的表格列1 = Table.ExpandTableColumn(删除的其他列1, "转换文件 (47)", Table.ColumnNames(#"转换文件 (47)"(#"示例文件 (47)"))),
				    更改的类型 = Table.TransformColumnTypes(扩展的表格列1,{{"Source.Name", type text}, {"客服", type text}, {"工作时间段咨询量", type number}, {"全天咨询量", type number}, {"接待量", type number}, {"首次30s接待量", type number}, {"首次30s应答率", Percentage.Type}, {"工作时间段无响应量", Int64.Type}, {"满意率", type text}, {"好评量", type number}, {"差评量", type number}, {"平均响应时间", type number}, {"平均响应时间（新标）", type number}, {"咨询差评率", Percentage.Type}, {"3分钟人工回复量", Int64.Type}, {"3分钟回复率（客服维度-不含留言）", type text}}),
				    筛选的行 = Table.SelectRows(更改的类型, each ([客服] <> "均值" and [客服] <> "总值")),
				    重命名的列 = Table.RenameColumns(筛选的行,{{"平均响应时间（新标）", "新平均响应时间"}}),
				    ExtractDate = Table.AddColumn(重命名的列, "日期", each 
				 let
				    FullText = [Source.Name],
				    
				    // 使用正则表达式思路提取日期（日） - 保持不变
				    DateMatch = Text.Select(Text.BetweenDelimiters(FullText, " ", " ", 1), {"0".."9"}),
				    Day = if DateMatch <> "" then Number.FromText(DateMatch) else null,
				    
				    // 月份查找 - 保持不变
				    Month = List.First(List.RemoveNulls(List.Transform(
				        {"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"},
				        (m) => if Text.Contains(FullText, m) then 
				            List.PositionOf({"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"}, m) + 1 
				            else null
				    )), null),
				    
				    // 提取年份 - 简化版直接查找4位数字
				    YearMatch = 
				        let
				            // 直接在整个文本中查找4位连续数字
				            // 方法1: 使用Text.PositionOf和Text.Middle
				            YearPattern = " " & Text.Combine(List.Transform({0..9}, Text.From)) & " ",
				            YearStart = Text.PositionOf(FullText, " CST ", Occurrence.First) + 5, // 找到第一个"CST "之后的位置
				            YearText = if YearStart > 4 then 
				                Text.Middle(FullText, YearStart, 4) else null,
				            Year = if YearText <> null and 
				                    Text.Length(Text.Select(YearText, {"0".."9"})) = 4 then 
				                Number.FromText(YearText) else null
				        in
				            Year,
				    
				    // 创建日期值
				    DateValue = try 
				        if Month <> null and Day <> null then 
				            if YearMatch <> null then 
				                #date(YearMatch, Month, Day)
				            else 
				                #date(2027, Month, Day)
				        else 
				            null 
				    otherwise null
				    
				in
				    DateValue)
				    ,
				    重命名的列3 = Table.RenameColumns(ExtractDate,{{"客服", "UID"}})
				in
				    重命名的列3
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

